services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activation-code-app
    working_dir: /app
    volumes:
      - ./数据:/app/data
    ports:
      - "7790:7790"
    environment:
      SYSTEM_CONFIG_PATH: "/app/data/系统配置.json"
      PORT: "7790"
